### PR TITLE
add eliminate

### LINKED ISSUE #40: A macro for local elimination (ZIO[A with B with C, ...] => C => ZIO[A with B])
Please write it :-)

### PR DESCRIPTION
**Pull request by mschuwalow**
resolves #40 

I don't know whether I'm happy with the API yet, but this infers better than everything else I've tried.
@ioleo Do you have any ideas?

/cc @iravid

### CODE REVIEW

**Review by iravid — COMMENTED** [review]
I love this! It’d be great to adopt a naming scheme similar to the non-macro combinators (e.g. providePart or something similar) and add it to the implicit classes in delegate.scala 💪

**Review by ioleo — APPROVED** [review]
Great addition :+1:

**Comment by mschuwalow** [comment]
> I love this! It’d be great to adopt a naming scheme similar to the non-macro combinators (e.g. providePart or something similar) and add it to the implicit classes in delegate.scala 💪

Agree that naming has room for improvement, but to be honest I don't have any ideas that I like.
What's your take?

**Comment by iravid** [comment]
Suggestions: `providePart`, `provideService`, `provideComponent`

**Comment by iravid** [comment]
Also renaming `provideSome` to `mapEnvironment` or something like that and reusing that name here.

**Comment by mschuwalow** [comment]
> Also renaming `provideSome` to `mapEnvironment` or something like that and reusing that name here.



> Also renaming `provideSome` to `mapEnvironment` or something like that and reusing that name here.

I like mapEnvironment much better. Alse when that name isn't taken anymore maybe provideSome is actually a good fit naming for name. Might be too confusing given its current use though

**Comment by mschuwalow** [comment]
@iravid @ioleo  I've renamed the syntax to providePart and also update usage.
Please take another look

**Review by iravid — APPROVED** [review]

**Pull request merged**
